services:
  postgresql:
    image: ankane/pgvector:latest
    container_name: postgresql
    ports:
      - '5678:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./shared/postgresql_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 8s
      retries: 5
    networks:
      - internal

  dagster_user_code:
    build:
      context: .
      dockerfile: ./Dockerfile_user_code
    container_name: dagster_user_code
    image: dagster_user_code_image
    restart: always
    expose:
      - "4000"
    environment:
      DAGSTER_POSTGRES_USER: ${DAGSTER_POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${DAGSTER_POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
      DAGSTER_CURRENT_IMAGE: ${DAGSTER_CURRENT_IMAGE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - internal

  dagster_webserver:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    container_name: dagster_webserver
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    expose:
      - '${DAGSTER_PORT}'
    ports:
      - '${DAGSTER_PORT}:3000'
    environment:
      DAGSTER_POSTGRES_USER: ${DAGSTER_POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${DAGSTER_POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - ./workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
    depends_on:
      postgresql:
        condition: service_healthy
      dagster_user_code:
        condition: service_started
    networks:
      - internal

  dagster_daemon:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    container_name: dagster_daemon
    entrypoint:
      - dagster-daemon
      - run
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: ${DAGSTER_POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${DAGSTER_POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - ./workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
    depends_on:
      postgresql:
        condition: service_healthy
      dagster_user_code:
        condition: service_started
    networks:
      - internal

  superset:
    build:
      context: .
      dockerfile: ./superset/Dockerfile
      args:
        SUPERSET_ADMIN: ${SUPERSET_ADMIN}
        SUPERSET_PASSWORD: ${SUPERSET_PASSWORD}
        SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    ports:
      - '${SUPERSET_PORT}:8088'
    command: gunicorn --bind  "0.0.0.0:8088" --access-logfile '-' --error-logfile '-' --workers 1 --worker-class gthread --threads 20 --timeout 60 --limit-request-line 0 --limit-request-field_size 0 "superset.app:create_app()"
    volumes:
      - ./shared/db:/app/superset_home/db
    depends_on:
      - dagster_daemon
      - dagster_webserver
      - postgresql
      - minio
    networks:
      - internal

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    ports:
      - '${MINIO_PORT}:9000'
      - '${MINIO_CONSOLE_PORT}:9001'
    volumes:
      - ./shared/minio_data:/data
    restart: always
    networks:
      - internal

networks:
  internal:
    driver: bridge
