version: "3.7"

services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    ports:
      - "5432:5432"
    volumes: # Make docker client accessible so we can terminate containers fro>
      - ./shared/postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres_db"]
      interval: 10s
      timeout: 8s
      retries: 5

  dagster_user_code:
    build:
      context: .
      dockerfile: ./Dockerfile_user_code
    container_name: dagster_user_code
    image: dagster_user_code_image
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      DAGSTER_CURRENT_IMAGE: "dagster_user_code"

  dagster_webserver:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    container_name: dagster_webserver
    image: dagster_webserver_image
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    volumes: # Make docker client accessible so we can terminate containers from the webserver
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./shared/dagster_home:/opt/dagster/dagster_home
    depends_on:
      postgresql:
        condition: service_healthy
      dagster_user_code:
        condition: service_started

  dagster_daemon:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    container_name: dagster_daemon
    image: dagster_daemon_image
    entrypoint:
      - dagster-daemon
      - run
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    volumes: # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./shared/dagster_home:/opt/dagster/dagster_home
    depends_on:
      postgresql:
        condition: service_healthy
      dagster_user_code:
        condition: service_started

  superset:
    build:
      context: .
      dockerfile: ./superset/Dockerfile
      args:
        SUPERSET_ADMIN: $SUPERSET_ADMIN
        SUPERSET_PASSWORD: $SUPERSET_PASSWORD
        SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    ports:
      - '8088:8088'
    command: gunicorn --bind  "0.0.0.0:8088" --access-logfile '-' --error-logfile '-' --workers 1 --worker-class gthread --threads 20 --timeout 60 --limit-request-line 0 --limit-request-field_size 0 "superset.app:create_app()"
    volumes:
      - ./shared/db:/app/superset_home/db
    depends_on:
      - dagster_daemon
      - dagster_webserver
      - postgresql
      - minio

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./shared/minio_data:/data
    restart: always
